name: manage-azure-policy-d6ee83f9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/V5_-_Azure_resources_should_be_locked_-_Audit_and_deploy_lock_66a9947d-7997-40ef-a9d7-9c778a0bb3b3/**'
#      - .github/workflows/manage-azure-policy-d6ee83f9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d6ee83f9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/V5_-_Azure_resources_should_be_locked_-_Audit_and_deploy_lock_66a9947d-7997-40ef-a9d7-9c778a0bb3b3/**
